Remove quickpull
Squashed commit of the following:

commit 9268e072c1e3fb3e7ca18e9e1a4fbf960657fd7b
Author: Omari Norman <omari@smileystation.com>
Date:   Sun Mar 22 11:10:32 2015 -0400

    modify .travis.yml

commit 4b9c1f00859c6e929803d30b164e0599857444b6
Author: Omari Norman <omari@smileystation.com>
Date:   Sun Mar 22 11:04:07 2015 -0400

    modify .travis.yml

commit 7c93548e3801f10894612b24e32ce4a073549a0f
Author: Omari Norman <omari@smileystation.com>
Date:   Sun Mar 22 10:52:38 2015 -0400

    modify .travis.yml

commit 056a4f0398fefbd86ccc744cf17685d688cf3165
Author: Omari Norman <omari@smileystation.com>
Date:   Sun Mar 22 10:45:21 2015 -0400

    modify .travis.yml

commit 9e6f6a12ee5874c67ab262afa4dc677c00361738
Author: Omari Norman <omari@smileystation.com>
Date:   Sun Mar 22 10:30:59 2015 -0400

    modify .travis.yml

commit f9abac8972eafa6979883ced16aaa3ac515b4a01
Author: Omari Norman <omari@smileystation.com>
Date:   Sun Mar 22 10:24:06 2015 -0400

    remove quickpull from .travis.yml

commit 043d091555345167a66fafe74a7fb0733a729960
Author: Omari Norman <omari@smileystation.com>
Date:   Sun Mar 22 09:52:21 2015 -0400

    WIP

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,21 +1,44 @@
-language: haskell
-ghc:
-  - 7.6
-  - 7.8
+# NB: don't set `language: haskell` here
+
+env:
+ - CABALVER=1.18 GHCVER=7.8.3
+ # - CABALVER=1.22 GHCVER=7.10.1
 
 before_install:
-  - cabal update
-  - cabal install cartel
-  - cabal install quickpull
-  - sh generate
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 
+install:
+ - cabal --version
+ - ghc-pkg list
+ - travis_retry cabal update
+ - cabal install cartel packdeps
+ - sh generate
+ - packdeps multiarg.cabal
+ - cabal install --only-dependencies --enable-tests
+
+# Here starts the actual work to be performed for the package under
+# test; any command which exits with a non-zero exit code causes the
+# build to fail.
 script:
-  - ghc-pkg list
-  - cabal sdist --output-directory=tarball
-  - cd tarball
-  - cabal configure --enable-tests
-  - cabal build
-  - cabal test
-  - cabal clean
-  - cabal configure -fprograms
-  - cabal build
+ - cabal configure --enable-tests -v2 -fprograms
+ - cabal build
+ - cabal test
+ - cabal check
+
+ # tests that a source-distribution can be generated
+ - cabal sdist
+
+ # check that the generated source-distribution can be built & installed
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
+
+# EOF
